import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import { ColorSchemeScript, MantineProvider, Loader } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import HeaderMegaMenu from "@/components/HeaderMegaMenu";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider defaultColorScheme="dark">
          <Suspense
            fallback={
              <div className="grid place-items-center min-h-screen">
                <Loader color="violet" type="dots" />
              </div>
            }
          >
            <Notifications />
            <HeaderMegaMenu />
            {children}
          </Suspense>
        </MantineProvider>
      </body>
    </html>
  );
}
